# Site settings

title: Patrick Berry Software
author: Patrick Berry
email: patrickberry961@gmail.com
description: >-
  Professional site of Patrick Berry, full stack software developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  patrickberry1
linkedin_username: patrickhberry

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
